### ISSUE TITLE
Ruch piona o 2 pola jest możliwy nawet kiedy stoi na tym polu inna figura

### ISSUE THREAD

**Issue by doublesz** [piotr-bocian/Projekt3-chess#3]
Kiedy pole na linii 4 (dla białych) lub 5 (dla czarnych) jest zajęte przez figurę dowolnego koloru - pionek nie powinien mieć możliwości ruszyć się na to pole. Tymczasem ruch jest możliwy. Dołączam screen dla zobrazowania problemu.
![Zrzut ekranu z 2021-02-12 00-10-30](https://user-images.githubusercontent.com/40668744/107711199-8aecd280-6cc7-11eb-8c38-e0fcdef8bf82.png)

**Comment by kwojc13** [comment]
naprawione na branchu enPassant-Pawn, czyli po mergu problem zniknie
